### ISSUE TITLE
EQA项目问题检索

### ISSUE THREAD

**Issue by aqvq** [aqvq/aqvq#9]
此issue用于记录在EQA项目遇到的各种问题及解决方案。

**Comment by aqvq** [comment]
### flash_attn安装问题

直接使用pip install或者conda install会报依赖版本冲突的错误。

参考[官方](https://github.com/Dao-AILab/flash-attention)给出的安装命令进行安装：

```bash
MAX_JOBS=4 pip install flash-attn --no-build-isolation
```

**Comment by aqvq** [comment]
### libOpenGL.so.0相关问题

运行`tutorials/play_game.py`可能会出现以下提示：

> ImportError: libOpenGL.so.0: cannot open shared object file: No such file or directory

使用conda环境，同时又没有管理员权限在本地安装软件，可以使用下面的命令直接在conda环境中安装缺失的库。

```bash
conda install libopengl libegl
```

当前habitat版本信息：

```txt
habitat-baselines         0.3.1                     dev_0    <develop>
habitat-lab               0.3.1                     dev_0    <develop>
habitat-sim               0.3.1                    pypi_0    pypi
```

**Comment by aqvq** [comment]
### GLIBCXX_X.X.XX问题

pytorch报错：

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/home/shangwentao/anaconda3/envs/eqacl/lib/python3.9/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /data1/home/shangwentao/anaconda3/envs/eqacl/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
```

解决办法：重新安装[pytorch](https://pytorch.org/get-started/locally/)

**Comment by aqvq** [comment]
### AttributeError: 'PrismaticVLM' object has no attribute '_supports_cache_class'

安装[flash-attention](https://github.com/Dao-AILab/flash-attention)

```bash
conda install flash-attn -c conda-forge -y
```

**Comment by aqvq** [comment]
### circular import

> ImportError: cannot import name 'is_fbcode' from partially initialized module 'torch._dynamo.config' (most likely due to a circular import) (/data1/home/shangwentao/anaconda3/envs/eqacl/lib/python3.9/site-packages/torch/_dynamo/config.py)

This likely is happening because you have multiple versions of torch installed. Run conda uninstall torch and then pip uninstall torch until they say that they do not have a version installed then try installing torch again.

```bash
# 把conda和pip的pytorch全部卸载
pip uninstall torch
conda uninstall torch

# 查看是否卸载完成
pip  list | grep torch
conda list | grep torch
```

从[PyTorch官网](https://pytorch.org/get-started/previous-versions/)重新下载

**Comment by aqvq** [comment]
### Huggingface网络问题

> 'huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.'

在python代码中设置环境变量

```python
import os
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
```

在运行python命令最前面设置环境变量

```bash
HF_ENDPOINT=https://hf-mirror.com python xxx.py python xxx.py
```

在命令行中设置环境变量

```bash
export HF_ENDPOINT=https://hf-mirror.com
```

**Comment by aqvq** [comment]
## Git加速

使用镜像站加速git，参考下面的例子，`your_name`是用户名，`your_token`是`access_token`，可以从[Github Settings](https://github.com/settings/tokens)设置，`ghp.ci`是镜像网站。

```bash
# 取消已有的url设置，如果没有跳过
git config --global --list
git config --global --unset url.[Tab补全]

# 设置加速域名
git config --global url.https://your_name:your_token@ghp.ci/github.com/.insteadof=https://github.com/
```

**Comment by aqvq** [comment]
### 加速HuggingFace

使用镜像网站`hf-mirror.com`

```bash
git config --global url."https://hf-mirror.com/".insteadOf https://huggingface.co/
```

不推荐使用git下载huggingface的模型。关于如何加速下载huggingceface可以参考[知乎 - 如何快速下载huggingface模型——全方法总结](https://zhuanlan.zhihu.com/p/663712983)，推荐[huggingface-model-downloader](https://gist.github.com/padeoe/697678ab8e528b85a2a7bddafea1fa4f)这个脚本，支持多线程，使用镜像站的情况下可以跑满带宽，还支持断点续传，在网络不佳的环境下能够稳定下载。

**Comment by aqvq** [comment]
### pip安装git仓库

修改后适合项目的`conda`的`environment.yml`示例：

```yaml
name: eqacl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - aihabitat
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=12.1
  - flash-attn
  - habitat-sim
  - withbullet
  - headless
  - libopengl
  - libegl
  - libnvjpeg
  - libpng
  - pip
  - pip:
    - accelerate
    - scikit-learn
    - scikit-image
    - magnum
    - loguru
    - tqdm
    - transformers
    - scipy
    - numba
    - "llava[standalone] @ git+https://github.com/LLaVA-VL/LLaVA-NeXT.git"
    - "habitat-lab @ git+https://github.com/facebookresearch/habitat-lab.git@stable#subdirectory=habitat-lab"
    - "prismatic @ git+https://github.com/TRI-ML/prismatic-vlms.git"
```

**更多内容参考**：
[pip install git(pip直接安装git上的项目)](https://blog.csdn.net/Castlehe/article/details/119532679)
[pip install from git repo branch](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)
[pip documentation v24.3.1](https://pip.pypa.io/en/stable/cli/pip_install/#examples)
